export const homePageContent = {
    displayBoard: {
        heroImage: {
            src: '/hero.png',
            alt: 'Hero Visione Vesuvio',
            width: 1060,
            height: 499,
        },
    },
    horizontalSlider: {
        ariaLabel: 'Selezione editoriale Visione Vesuvio',
        items: [
            { id: 'slider-01', src: '/slider/slider_01.png', alt: 'Slider poster 1', width: 480, height: 720 },
            { id: 'slider-02', src: '/slider/slider_02.png', alt: 'Slider poster 2', width: 480, height: 720 },
            { id: 'slider-03', src: '/slider/slider_03.png', alt: 'Slider poster 3', width: 480, height: 720 },
            { id: 'slider-04', src: '/slider/slider_04.png', alt: 'Slider poster 4', width: 480, height: 720 },
            { id: 'slider-05', src: '/slider/slider_05.png', alt: 'Slider poster 5', width: 480, height: 720 },
            { id: 'slider-06', src: '/slider/slider_06.png', alt: 'Slider poster 6', width: 480, height: 720 },
            { id: 'slider-07', src: '/slider/slider_07.png', alt: 'Slider poster 7', width: 480, height: 720 },
            { id: 'slider-08', src: '/slider/slider_08.png', alt: 'Slider poster 8', width: 480, height: 720 },
        ],
    },
    shopShowcase: {
        title: 'Shop',
        cta: {
            label: 'Scopri di piu',
            href: '/store',
        },
        items: [
            {
                id: 'suonne-ammore-01',
                src: '/film/fire_of_love.png',
                alt: 'Poster Fire of Love',
                width: 480,
                height: 720,
            },
            { id: 'fallen-angels', src: '/film/fallen_angels.png', alt: 'Poster Fallen Angels', width: 480, height: 720 },
            { id: 'kill-bill', src: '/film/kill_bill_1.png', alt: 'Poster Kill Bill', width: 480, height: 720 },
            { id: 'in-the-mood', src: '/film/in_the_mood_for_love.png', alt: 'Poster In the Mood for Love', width: 480, height: 720 },
            { id: 'souffle', src: '/film/souffle.png', alt: 'Poster A bout de souffle', width: 480, height: 720 },
            { id: 'suonne-ammore-02', src: '/film/her.png', alt: 'Poster Her', width: 480, height: 720 },
            { id: 'blue-velvet', src: '/film/blue_velvet.png', alt: 'Poster Blue Velvet', width: 480, height: 720 },
            { id: 'paris-texas', src: '/film/paris_texas.png', alt: 'Poster Paris, Texas', width: 480, height: 720 },
            { id: 'city-of-god', src: '/film/city_of_god.png', alt: 'Poster City of God', width: 480, height: 720 },
        ],
    },
    rassegnePreview: {
        title: 'Rassegne',
        status: 'In corso',
        images: [
            {
                id: 'rassegna-ex-machina',
                src: '/film/ex_machina.png',
                alt: 'Still rassegna Suonne e Ammore',
                width: 200,
                height: 300,
            },
            {
                id: 'rassegna-her',
                src: '/film/her.png',
                alt: 'Still rassegna Her',
                width: 200,
                height: 300,
            },
            {
                id: 'rassegna-blue-velvet',
                src: '/film/blue_velvet.png',
                alt: 'Still rassegna Blue Velvet',
                width: 200,
                height: 300,
            },
        ],
        image: {
            src: '/film/ex_machina.png',
            alt: 'Still rassegna Suonne e Ammore',
            width: 200,
            height: 300,
        },
        tags: ['Cinema all\'aperto', 'Villa Floridiana', 'DJ set'],
        heading: 'Suonne e Ammore',
        subtitle: 'con il Cinema Plaza',
        description: 'Visione Vesuvio presenta: Suonne e Ammore, seconda edizione del cinema all\'aperto che accompagna l\'estate Partenopea.',
    },
    programSection: {
        kicker: 'Programmazione',
        title: 'Estate 2K25',
        description: 'Una selezione settimanale di titoli da vivere insieme, tra romanticismo nevrotico, fantascienza malinconica e cult da riscoprire all\'aperto.',
        primaryCta: {
            label: 'Vedi tutto il programma',
            href: '/programmazione',
        },
        secondaryCta: {
            label: 'Scopri le rassegne',
            href: '/rassegne',
        },
        featuredVisual: {
            src: '/film/blue_velvet.png',
            alt: 'Visual programmazione',
            width: 1000,
            height: 1400,
        },
        voiceLabel: 'V.O.S.',
        events: [
            {
                id: 'planete-sauvage',
                date: 'Giovedi 7 maggio',
                title: 'Il pianeta selvaggio',
                originalTitle: 'La planete sauvage',
                director: 'Rene Laloux',
                venue: 'Villa Floridiana, Napoli',
            },
            {
                id: 'blue-velvet-home',
                date: 'Martedi 7 maggio',
                title: 'Velluto Blu',
                originalTitle: 'Blue Velvet',
                director: 'David Lynch',
                venue: 'Villa Floridiana, Napoli',
            },
            {
                id: 'annie-hall-home',
                date: 'Martedi 7 maggio',
                title: 'Io e Annie',
                originalTitle: 'Annie Hall',
                director: 'Woody Allen',
                venue: 'Villa Floridiana, Napoli',
            },
            {
                id: 'otto-e-mezzo-home',
                date: 'Martedi 7 maggio',
                title: 'Otto e mezzo',
                originalTitle: '',
                director: 'Federico Fellini',
                venue: 'Villa Floridiana, Napoli',
            },
        ],
    },
    manifesto: {
        title: 'Visione Vesuvio promuove la cultura cinematografica, riportando al centro il valore dell\'esperienza di visione condivisa.',
        supportingText: 'Ogni blocco del sito deve potersi trasformare in contenuto editoriale gestibile, senza perdere coerenza tipografica, ritmo e identita visiva.',
    },
    gallery: [
        {
            id: 'season-mark',
            src: '/poster.png',
            alt: 'Artwork tipografico della stagione',
            width: 2048,
            height: 1228,
        },
        {
            id: 'event-photo',
            src: '/S&A.png',
            alt: 'Artwork grafico Visione Vesuvio',
            width: 2048,
            height: 1228,
        },
    ],
    shopTeaser: {
        title: 'Shop',
        description: 'Poster, edizioni e oggetti pensati come estensioni fisiche delle rassegne.',
        cta: {
            label: 'Vai allo shop',
            href: '/store',
        },
    },
};
