import { getVisibleItems } from '@/app/content/utils';

export const programEvents = [
    {
        id: 'in-the-mood-for-love',
        slug: 'in-the-mood-for-love',
        order: 10,
        isVisible: true,
        isFeaturedOnHome: true,
        shortLabel: '05 Lug',
        fullDateLabel: 'Domenica 05/07/26',
        title: 'IN THE MOOD FOR LOVE',
        poster: {
            src: '/film/in_the_mood_for_love.png',
            alt: 'Locandina In The Mood For Love',
            width: 200,
            height: 300,
        },
        trailer: {
            youtubeVideoId: 'm8GuedsQnWQ?si=dqUYh6jnDQ9p3Yob',
        },
        venue: 'Villa Floridiana, Napoli',
        entryTime: 'Ingresso dalle ore 20:00',
        startTime: 'Inizio proiezione ore 21:00',
        description: 'A Hong Kong negli anni \'60 due anime ferite si incontrano nell\'intimita di corridoi e sguardi rubati. In un crescendo di desiderio trattenuto, l\'amore nasce dove non puo compiersi.',
        directors: ['Wong Kar-wai'],
        duration: '98 min',
        year: '2000',
        country: 'Hong Kong, Francia',
        language: 'Cantonese, shanghainese, francese',
        ticketUrl: 'https://floridiana.plazanapoli.18tickets.it/film/20921',
    },
    {
        id: 'her',
        slug: 'her',
        order: 20,
        isVisible: true,
        isFeaturedOnHome: true,
        shortLabel: '12 Lug',
        fullDateLabel: 'Domenica 12/07/26',
        title: 'HER',
        poster: {
            src: '/film/her.png',
            alt: 'Locandina Her',
            width: 200,
            height: 300,
        },
        trailer: {
            youtubeVideoId: 'YzS77icrzD0?si=YEgug53iBlspc6YG',
        },
        venue: 'Villa Floridiana, Napoli',
        entryTime: 'Ingresso dalle ore 20:00',
        startTime: 'Inizio proiezione ore 21:00',
        description: 'In un futuro vicino, un uomo solitario si innamora di un\'intelligenza artificiale. Un racconto toccante sull\'amore, la tecnologia e la solitudine.',
        directors: ['Spike Jonze'],
        duration: '126 min',
        year: '2013',
        country: 'Stati Uniti',
        language: 'Inglese',
        ticketUrl: 'https://floridiana.plazanapoli.18tickets.it/film/20922',
    },
    {
        id: 'ex-machina',
        slug: 'ex-machina',
        order: 30,
        isVisible: true,
        isFeaturedOnHome: true,
        shortLabel: '19 Lug',
        fullDateLabel: 'Domenica 19/07/26',
        title: 'EX MACHINA',
        poster: {
            src: '/film/ex_machina.png',
            alt: 'Locandina Ex Machina',
            width: 200,
            height: 300,
        },
        trailer: {
            youtubeVideoId: 'EoQuVnKhxaM?si=zBImMqBMPTVGf9QM',
        },
        venue: 'Villa Floridiana, Napoli',
        entryTime: 'Ingresso dalle ore 20:00',
        startTime: 'Inizio proiezione ore 21:00',
        description: 'Un giovane programmatore partecipa a un test sull\'intelligenza artificiale in una villa isolata. La linea tra umano e artificiale si fa inquietante.',
        directors: ['Alex Garland'],
        duration: '108 min',
        year: '2014',
        country: 'Regno Unito',
        language: 'Inglese',
        ticketUrl: 'https://floridiana.plazanapoli.18tickets.it/film/20923',
    },
    {
        id: 'annie-hall',
        slug: 'annie-hall',
        order: 40,
        isVisible: true,
        isFeaturedOnHome: true,
        shortLabel: '26 Lug',
        fullDateLabel: 'Domenica 26/07/26',
        title: 'ANNIE HALL',
        poster: {
            src: '/film/hannie_hall.png',
            alt: 'Locandina Annie Hall',
            width: 200,
            height: 300,
        },
        trailer: {
            youtubeVideoId: 'OqVgCfZX-yE?si=ILfA60vJLMdw0m0A',
        },
        venue: 'To be defined.',
        entryTime: 'Ingresso dalle ore 20:00',
        startTime: 'Inizio proiezione ore 21:00',
        description: 'Un comico nevrotico di New York ripercorre la sua storia d\'amore con la stravagante Annie. Ironico e profondo, e un cult della commedia romantica.',
        directors: ['Woody Allen'],
        duration: '93 min',
        year: '1977',
        country: 'Stati Uniti',
        language: 'Inglese',
        ticketUrl: 'https://floridiana.plazanapoli.18tickets.it/',
    },
    {
        id: 'alice-in-wonderland',
        slug: 'alice-in-wonderland',
        order: 50,
        isVisible: true,
        isFeaturedOnHome: true,
        shortLabel: '02 Ago',
        fullDateLabel: 'Domenica 02/08/26',
        title: 'ALICE IN WONDERLAND (1951)',
        poster: {
            src: '/film/alice.png',
            alt: 'Locandina Alice in Wonderland (1951)',
            width: 200,
            height: 300,
        },
        trailer: {
            youtubeVideoId: 'XMVwQcjn3NY?si=dsM2B875fma3oSYv',
        },
        venue: 'To be defined.',
        entryTime: 'Ingresso dalle ore 20:00',
        startTime: 'Inizio proiezione ore 21:00',
        description: 'Il classico d\'animazione Disney che segue la curiosa Alice nel suo viaggio in un mondo assurdo e incantato. Un\'esplosione di fantasia e immaginazione.',
        directors: ['Clyde Geronimi', 'Wilfred Jackson', 'Hamilton Luske'],
        duration: '75 min',
        year: '1951',
        country: 'Stati Uniti',
        language: 'Inglese',
        ticketUrl: 'https://floridiana.plazanapoli.18tickets.it/',
    },
    {
        id: 'blue-velvet',
        slug: 'blue-velvet',
        order: 60,
        isVisible: true,
        isFeaturedOnHome: true,
        shortLabel: '09 Ago',
        fullDateLabel: 'Domenica 09/08/26',
        title: 'BLUE VELVET',
        poster: {
            src: '/film/blue_velvet.png',
            alt: 'Locandina Blue Velvet',
            width: 200,
            height: 300,
        },
        trailer: {
            youtubeVideoId: 'rAA6imfqMYQ',
        },
        venue: 'To be defined.',
        entryTime: 'Ingresso dalle ore 20:00',
        startTime: 'Inizio proiezione ore 21:00',
        description: 'Un giovane scopre un misterioso orecchio umano in un campo. Lynch mescola noir e incubo in un\'indagine sul lato oscuro della provincia americana.',
        directors: ['David Lynch'],
        duration: '120 min',
        year: '1986',
        country: 'Stati Uniti',
        language: 'Inglese',
        ticketUrl: 'https://floridiana.plazanapoli.18tickets.it/',
    },
    {
        id: 'brazil',
        slug: 'brazil',
        order: 70,
        isVisible: true,
        isFeaturedOnHome: true,
        shortLabel: '16 Ago',
        fullDateLabel: 'Domenica 16/08/26',
        title: 'BRAZIL',
        poster: {
            src: '/film/brazil.png',
            alt: 'Locandina Brazil',
            width: 200,
            height: 300,
        },
        trailer: {
            youtubeVideoId: '4Gqjdscj3e8?si=DK7Asl-4lDDzZObc',
        },
        venue: 'To be defined.',
        entryTime: 'Ingresso dalle ore 20:00',
        startTime: 'Inizio proiezione ore 21:00',
        description: 'Un impiegato vive in un futuro distopico dominato dalla burocrazia. Tra sogno e incubo, una satira grottesca del controllo e della liberta.',
        directors: ['Terry Gilliam'],
        duration: '132 min',
        year: '1985',
        country: 'Regno Unito',
        language: 'Inglese',
        ticketUrl: 'https://floridiana.plazanapoli.18tickets.it/',
    },
    {
        id: 'otto-e-mezzo',
        slug: 'otto-e-mezzo',
        order: 80,
        isVisible: true,
        isFeaturedOnHome: true,
        shortLabel: '23 Ago',
        fullDateLabel: 'Domenica 23/08/26',
        title: '8 1/2',
        poster: {
            src: '/film/8_1_2.png',
            alt: 'Locandina 8 1/2',
            width: 200,
            height: 300,
        },
        trailer: {
            youtubeVideoId: 'RmIC9pQ80Fk?si=WFoplnBk-wJkpSUb',
        },
        venue: 'To be defined.',
        entryTime: 'Ingresso dalle ore 20:00',
        startTime: 'Inizio proiezione ore 21:00',
        description: 'Un regista in crisi creativa si perde nei suoi sogni, ricordi e fantasie. Fellini firma un capolavoro sul caos interiore dell\'artista.',
        directors: ['Federico Fellini'],
        duration: '138 min',
        year: '1963',
        country: 'Italia, Francia',
        language: 'Italiano',
        ticketUrl: 'https://floridiana.plazanapoli.18tickets.it/',
    },
    {
        id: 'paris-texas',
        slug: 'paris-texas',
        order: 90,
        isVisible: true,
        isFeaturedOnHome: true,
        shortLabel: '30 Ago',
        fullDateLabel: 'Domenica 30/08/26',
        title: 'PARIS, TEXAS',
        poster: {
            src: '/film/paris_texas.png',
            alt: 'Locandina Paris, Texas',
            width: 200,
            height: 300,
        },
        trailer: {
            youtubeVideoId: '3j8ypqxfiT4?si=SpBDMBw3O4BrwHR9',
        },
        venue: 'To be defined.',
        entryTime: 'Ingresso dalle ore 20:00',
        startTime: 'Inizio proiezione ore 21:00',
        description: 'Un uomo ricompare dopo anni di assenza, cercando di ricostruire il rapporto con il figlio. Un viaggio silenzioso e toccante tra solitudine e redenzione.',
        directors: ['Wim Wenders'],
        duration: '147 min',
        year: '1984',
        country: 'Germania Ovest, Francia, Regno Unito',
        language: 'Inglese',
        ticketUrl: 'https://floridiana.plazanapoli.18tickets.it/',
    },
];

export function getProgramEvents() {
    return getVisibleItems(programEvents);
}

export function getHomepageFeaturedProgramEvents() {
    return getProgramEvents().filter((event) => event.isFeaturedOnHome);
}
